accounts/urls.py
from django.conf.urls import url

from accounts.views import UserprofileList, UserprofileDetalhe, UserprofileUpdate, userprofile_delete

app_name = 'accounts'

urlpatterns = [

    url(r'^userprofile-list/$', UserprofileList.as_view(), name='userprofile-list'),
    url(r'^userprofile-list/(?P<pk>[0-9]+)/$', UserprofileDetalhe.as_view(), name='userprofile-detail'),
    url(r'^userprofile/(?P<pk>[0-9]+)/edit/$', UserprofileUpdate.as_view(), name='userprofile-edit'),
    url(r'^userprofile/(?P<id>[0-9]+)/delete/$', userprofile_delete, name='userprofile-delete'),

]

contabilidade/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView

from accounts import views as accounts_views
from ctb import views

urlpatterns = [
                  url(r'^$', views.index, name='index'),
                  url(r'^cart/', include('cart.urls')),
    url(r'^acc/', include('accounts.urls')),
    url(r'^ctb/', include('ctb.urls')),
    url(r'^admin/', admin.site.urls, name='admin'),

                  #
    # AUTENTICAÇÃO
    #
    url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
                  url(r'^signup/$', accounts_views.signup, name='signup'),

    url(r'^reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='password_reset.html',
            email_template_name='password_reset_email.html',
            subject_template_name='password_reset_subject.txt'
        ),
        name='password_reset'),
    url(r'^reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
        name='password_reset_confirm'),
    url(r'^reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
        name='password_reset_complete'),

    url(r'^settings/password/$', auth_views.PasswordChangeView.as_view(template_name='password_change.html'),
        name='password_change'),
    url(r'^settings/password/done/$', auth_views.PasswordChangeDoneView.as_view(
        template_name='password_change_done.html'), name='password_change_done'),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'ctb.views.error_404'
handler500 = 'ctb.views.error_500'

ctb/urls.py
from django.conf.urls import url

from ctb import views
from ctb.views import CompetenciaList, CompetenciaDetalhe, CompetenciaCreate, CompetenciaUpdate, competencia_delete, \
    ContaList, ContaDetalhe, ContaCreate, ContaUpdate, conta_delete, \
    EmpresaList, EmpresaDetalhe, EmpresaCreate, EmpresaUpdate, empresa_delete, \
    HistoricoList, HistoricoDetalhe, HistoricoCreate, HistoricoUpdate, historico_delete, MovimentoContabilHeaderList, \
    MovimentoContabilHeaderCreate, MovimentoContabilHeaderUpdate, movimento_contabil_header_delete, \
    MovimentoContabilHeaderDetalhe, SaldoContaContabilList, SaldoDetalhe, RazaoContabilList, \
    CreateMovimentoContabilHeader, GeneratePdf

app_name = 'ctb'

urlpatterns = [
    # url(r'^$', views.index, name='index'),
    url(r'^home/', views.home, name='home'),

    # Contas
    url(r'^conta-list/$', ContaList.as_view(), name='conta-list'),
    url(r'^conta-list/(?P<pk>[0-9]+)/$', ContaDetalhe.as_view(), name="conta-detail"),
    url(r'^conta-add/$', ContaCreate.as_view(), name='conta-add'),
    url(r'^conta/(?P<pk>[0-9]+)/edit/$', ContaUpdate.as_view(), name='conta-edit'),
    url(r'^conta/(?P<id>[0-9]+)/delete/$', conta_delete, name='conta-delete'),

    # Historicos
    url(r'^historico-list/$', HistoricoList.as_view(), name='historico-list'),
    url(r'^historico-list/(?P<pk>[0-9]+)/$', HistoricoDetalhe.as_view(), name='historico-detail'),
    url(r'^historico-add/$', HistoricoCreate.as_view(), name='historico-add'),
    url(r'^historico/(?P<pk>[0-9]+)/edit/$', HistoricoUpdate.as_view(), name='historico-edit'),
    url(r'^historico/(?P<id>[0-9]+)/delete/$', historico_delete, name='historico-delete'),

    # Empresas
    url(r'^empresa-list/$', EmpresaList.as_view(), name='empresa-list'),
    url(r'^empresa-list/(?P<pk>[0-9]+)/$', EmpresaDetalhe.as_view(), name="empresa-detail"),
    url(r'^empresa-add/$', EmpresaCreate.as_view(), name='empresa-add'),
    url(r'^empresa/(?P<pk>[0-9]+)/edit/$', EmpresaUpdate.as_view(), name='empresa-edit'),
    url(r'^empresa/(?P<id>[0-9]+)/delete/$', empresa_delete, name='empresa-delete'),

    # Competências
    url(r'^competencia-list/$', CompetenciaList.as_view(), name='competencia-list'),
    url(r'^competencia-list/(?P<pk>[0-9]+)/$', CompetenciaDetalhe.as_view(), name='competencia-detail'),
    url(r'^competencia-add/$', CompetenciaCreate.as_view(), name='competencia-add'),
    url(r'^competencia/(?P<pk>[0-9]+)/edit/$', CompetenciaUpdate.as_view(), name='competencia-edit'),
    url(r'^competencia/(?P<id>[0-9]+)/delete/$', competencia_delete, name='competencia-delete'),

    # FORMSET: Lancamento Contabil
    url(r'^lanc-add/$', CreateMovimentoContabilHeader.as_view(), name='lanc-add'),


    # Movimentos Header
    url(r'^movimento-list/$', MovimentoContabilHeaderList.as_view(), name='movimento-list'),
    url(r'^movimento-detalhe/(?P<pk>[0-9]+)/$', MovimentoContabilHeaderDetalhe.as_view(), name='movimento-detail'),
    url(r'^movimento-add/$', MovimentoContabilHeaderCreate.as_view(), name='movimento-add'),
    url(r'^movimento/(?P<pk>[0-9]+)/edit/$', MovimentoContabilHeaderUpdate.as_view(), name='movimento-edit'),
    url(r'^movimento/(?P<id>[0-9]+)/delete/$', movimento_contabil_header_delete, name='movimento-delete'),

    # Lançamentos
    url(r'^(?P<movimentocontabilheader_id>[0-9]+)/create_lancamento/$', views.create_lancamento,
        name='lancamento-add'),
    url(r'^(?P<movimentocontabilheader_id>[0-9]+)/delete_lancamento/(?P<lancamentocontabil_id>[0-9]+)/$',
        views.delete_lancamento, name='lancamento-delete'),
    url(r'^razao_contabil/$', RazaoContabilList.as_view(), name='razao_contabil'),

    # saldo
    url(r'^saldo-lista/$', SaldoContaContabilList.as_view(), name='saldo-list'),
    url(r'^saldo-detalhe/(?P<pk>[0-9]+)/$', SaldoDetalhe.as_view(), name='saldo-detail'),

    # WORK IN PROGRESS
    url(r'^wip/$', views.work_in_progress, name="wip"),

    # ReportLab
    url(r'^pdf/$', GeneratePdf.as_view(), name='generate_pdf'),

]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import post_save
from django.urls import reverse

from choices.models import SIM_NAO_CHOICES
from glb.models import GlobalCodigoEstado


# Create your models here.


class UserProfile(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)
    nome = models.CharField(max_length=50, default='')
    apelido = models.CharField(max_length=50, default='', null=True, blank=True)
    endereco = models.CharField(max_length=50, default='', null=True, blank=True)
    complemento = models.CharField(max_length=50, default='', null=True, blank=True)
    cep = models.IntegerField(default=0, null=True, blank=True)
    bairro = models.CharField(max_length=30, default='Bairro')
    cidade = models.CharField(max_length=50, default='Cidade')
    uf = models.ForeignKey(GlobalCodigoEstado, default='', null=True, blank=True, on_delete=models.CASCADE)
    # Login e Senha vem da tabela User
    nivel_acesso = models.IntegerField(default=0)
    supervisor = models.BooleanField(default=False)
    segunda_feira = models.BooleanField(default=True)
    segunda_hora_inicio = models.TimeField(default='8:00', blank=True, null=True)
    segunda_hora_final = models.TimeField(default='17:00', blank=True, null=True)
    terca_feira = models.BooleanField(default=True)
    terca_hora_inicio = models.TimeField(default='8:00', blank=True, null=True)
    terca_hora_final = models.TimeField(default='17:00', blank=True, null=True)
    quarta_feira = models.BooleanField(default=True)
    quarta_hora_inicio = models.TimeField(default='8:00', blank=True, null=True)
    quarta_hora_final = models.TimeField(default='17:00', blank=True, null=True)
    quinta_feira = models.BooleanField(default=True)
    quinta_hora_inicio = models.TimeField(default='8:00', blank=True, null=True)
    quinta_hora_final = models.TimeField(default='17:00', blank=True, null=True)
    sexta_feira = models.BooleanField(default=True)
    sexta_hora_inicio = models.TimeField(default='8:00', blank=True, null=True)
    sexta_hora_final = models.TimeField(default='17:00', blank=True, null=True)
    sabado = models.BooleanField(default=True)
    sabado_hora_inicio = models.TimeField(default='8:00', blank=True, null=True)
    sabado_hora_final = models.TimeField(default='17:00', blank=True, null=True)
    domingo = models.BooleanField(default=False)
    domingo_hora_inicio = models.TimeField(default='8:00', blank=True, null=True)
    domingo_hora_final = models.TimeField(default='17:00', blank=True, null=True)
    opera_caixa = models.BooleanField(default=False)
    numero_checkout = models.IntegerField(null=True, default=0)
    comprador = models.BooleanField(default=False)
    limite_por_compra = models.DecimalField(max_digits=16, decimal_places=2, default=0)
    limite_compra = models.DecimalField(max_digits=16, decimal_places=2, default=0)
    funcionario = models.CharField(max_length=3, choices=SIM_NAO_CHOICES, default='Sim')
    vendedor = models.CharField(max_length=3, choices=SIM_NAO_CHOICES, default='Não')
    codigo_supervisor = models.IntegerField(null=True, default=0)  # Auto relacionamento
    comissao_venda = models.DecimalField(max_digits=14, decimal_places=2, default=0)
    comissao_sobre_servicos = models.DecimalField(max_digits=14, decimal_places=2, default=0)
    objetivo_mensal_vendas = models.DecimalField(max_digits=14, decimal_places=2, default=0)
    banco_numero = models.IntegerField(null=True, default=0)
    banco_agencia = models.IntegerField(null=True, default=0)
    banco_digito_verficador = models.IntegerField(null=True, default=0)
    data_nascimento = models.DateField(null=True, blank=True, default='2009-12-31')
    regiao_venda = models.CharField("Região de Venda", max_length=13, default='', blank=True, null=True)
    departamento = models.CharField(max_length=15, default='', blank=True, null=True)
    matricula = models.CharField(max_length=20, default='', blank=True, null=True)
    # Grupo vem da tabela User
    identidade = models.CharField(max_length=20, blank=True, null=True)
    data_emissao = models.DateField(blank=True, null=True, default='2009-12-31')
    orgao_emissor = models.CharField(max_length=10, blank=True, null=True)
    fisica_juridica = models.CharField(max_length=1, default='F')
    cpf_cnpj = models.IntegerField(default=0)
    sexo = models.CharField(max_length=1, default='M')
    ddd_residencia = models.IntegerField(null=True, default=0)
    tel_residencia = models.IntegerField(null=True, default=0)
    ddd_celular = models.IntegerField(null=True, default=0)
    tel_celular = models.IntegerField(null=True, default=0)
    informacoes_adicionais = models.TextField(max_length=256, default='', blank=True, null=True)
    email = models.EmailField(max_length=50, default='usuario@email.com')

    def get_absolute_url(self):
        return reverse('acc:userprofile-detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.nome

    class Meta:
        ordering = ('nome',)
        verbose_name = 'Perfil de Usuário'
        verbose_name_plural = 'Perfis de Usuário'


"""
    SIGNALS
"""


def create_profile(sender, **kwargs):
    if kwargs['created']:
        user_profile = UserProfile.objects.create(usuario=kwargs['instance'])

post_save.connect(create_profile, sender=User)

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    email = forms.CharField(max_length=254, required=True, widget=forms.EmailInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

accounts/views.py
from django.contrib import messages
from django.contrib.auth import login as auth_login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import ListView, DetailView, UpdateView

from accounts.models import UserProfile


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('index')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})


class UserprofileList(SuccessMessageMixin, LoginRequiredMixin, ListView):
    model = UserProfile
    template_name = 'accounts/userprofile/userprofile-list.html'

    def get_queryset(self):
        nome = self.request.GET.get('q')
        if nome:
            object_list = self.model.objects.filter(nome__icontains=nome)
        else:
            object_list = self.model.objects.all()

        paginator = Paginator(object_list, 9)  # Show 9 contas per page

        page = self.request.GET.get('page')
        try:
            queryset = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            queryset = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            queryset = paginator.page(paginator.num_pages)

        # return object_list
        return queryset


class UserprofileDetalhe(SuccessMessageMixin, LoginRequiredMixin, DetailView):
    model = UserProfile
    template_name = 'accounts/userprofile/userprofile_detail.html'


class UserprofileUpdate(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = UserProfile
    template_name = 'accounts/userprofile/userprofile_form.html'
    fields = '__all__'
    success_message = '%(nome) alterado com sucesso!'

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            calculated_field=self.object.nome,
        )


def userprofile_delete(request, id=None):
    obj = get_object_or_404(UserProfile, id=id)
    if request.method == 'POST':
        obj.delete()
        messages.success(request, 'Registro apagado com sucesso!')
        return redirect('acc:userprofile-list')

    context = {
        'object': obj
    }

    return render(request, 'ctb/confirm_delete.html', context)

templates/accounts/userprofile/userprofile-list.html
{% extends 'ctb/base_sidebar.html' %}
{% block conta_active %}active{% endblock %}

{% block body %}

    <!-- contas -->
    <div class="col-md-offset-3">
        <div class="panel panel-default">
            <div class="container">

                <div class="col-md-2">
                    <h4 style="margin-left: 10px; margin-top: 10px;"><strong>Usuários</strong></h4>
                </div>

                <!-- Pesquisa -->
                <div class="col-md-4">
                    <form method="GET" action="" id="searchform" style="margin-top: 0px;">
                        {% csrf_token %}
                        <input class="input-lg input-search" id="searchbox" name="q" type="text" value="{{ request.GET.q }}"
                            placeholder="Pesquisa Contas..."/>
                    </form>
                </div>

                <div class="btn-group">


                    <!-- PDF -->
                    <a href="#">
                        <button type="button" disabled class="btn btn-warning" data-toggle="tooltip" title="Gera PDF"
                                style="margin-top: 4px;">
                            <span class="glyphicon glyphicon-download-alt"></span>&nbsp; PDF
                        </button>
                    </a>

                    <!-- EXCEL -->
                    <a href="#">
                        <button type="button" disabled class="btn btn-warning" data-toggle="tooltip" title="Gera Excel"
                                style="margin-top: 4px;">
                            <span class="glyphicon glyphicon-download-alt"></span>&nbsp; Excel
                        </button>
                    </a>

                    <!-- Botão Cria Registro -->
                    <!-- ESSE REGISTRO É CRIADO AUTOMATICAMENTE TODA VEZ QUE UM USUARIO DO SISTEMA É CRIADO VIA
                         Admin -->
                    <a href="#">
                        <button type="button" disabled class="btn btn-success"  data-toggle="tooltip" title="Cria um novo registro"
                                style="margin-top: 4px;">
                            <span class="glyphicon glyphicon-plus"></span>&nbsp; Novo registro
                        </button>
                    </a>

                </div>
            </div>

        </div>
        {% if object_list %}
                <table class=" responsive table table-responsive table-condensed table-bordered table-hover table-striped"
                   style="margin-bottom: 0px;">
                    <tbody>
                        <tr>
                            <th>Nome de Usuário</th>
                            <th>Nome</th>
                            <th>Apelido</th>
                        </tr>
                        <tfoot>
                            <tr>
                                <th>Nome de Usuário</th>
                                <th>Nome</th>
                                <th>Apelido</th>
                            </tr>
                        </tfoot>
                        {% for userprofile in object_list %}
                            <tr>

                                <td> <a href="{% url 'accounts:userprofile-detail' userprofile.id %}">{{ userprofile.usuario }}</a></td>
                                <td><a href="{% url 'accounts:userprofile-detail' userprofile.id %}">{{ userprofile.nome }}</a></td>
                                <td><a href="{% url 'accounts:userprofile-detail' userprofile.id %}">{{ userprofile.apelido }}</a></td>

                                <!-- Edita -->
                                <td>
                                 <a href="{% url 'accounts:userprofile-edit' userprofile.id %}"
                                        class="btn btn-primary btn-sm" role="button" data-toggle="tooltip"
                                        title="Altera o registro">
                                        <span class="glyphicon glyphicon-edit"></span></a>

                                <!-- Deleta -->
                                    <form action="{% url 'accounts:userprofile-delete' userprofile.id %}"
                                           style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="conta_id" value="{{ conta.id }}" />
                                            <button type="submit" disabled class="btn btn-danger btn-sm" data-toggle="tooltip"
                                                    title="Exclui o registro">
                                                <span class="glyphicon glyphicon-trash"></span>
                                            </button>
                                    </form>
                                </td>
                            </tr>
                        {% endfor %}


                    </tbody>

                    <script>
                         $(document).ready(function(){
                         $('[data-toggle="tooltip"]').tooltip();
                          });
                    </script>

                </table>

                <div class="col-md-offset-3" align="right">
                    <div class="pagination">
                        <span class="step-links">
                            {% if object_list.has_previous %}
                                <a href="?page={{ object_list.previous_page_number }}">
                                    <span data-toggle="tooltip" title="Página anterior" class="glyphicon glyphicon-triangle-left" aria-hidden="true"></span></a>
                            {% endif %}

                            <span class="current">
                                Página {{ object_list.number }} de {{ object_list.paginator.num_pages }}
                            </span>

                            {% if object_list.has_next %}
                                <a href="?page={{ object_list.next_page_number }}">
                                    <span data-toggle="tooltip" title="Página seguinte" class="glyphicon glyphicon-triangle-right" aria-hidden="true"></span></a>
                            {% endif %}
                        </span>
                    </div>
                </div>


        {% else %}
            <h1>Não existem Perfis de Usuários Cadastrados</h1>
        {% endif %}
    </div>



{% endblock %}

templates/accounts/userprofile/userprofile_detail.html
{% extends 'ctb/base_sidebar.html' %}


{% block body %}
<div class="col-md-offset-3">

    <h1>Detalhes do Perfil do usuário: {{ userprofile.usuario }}</h1>
    <div class="col-sm-4 col-md-6">
        <div class="panel panel-default">
            <div class="panel-body">

                {% if user.is_superuser %}
                <a href="{% url 'accounts:userprofile-list' %}">
                        <span class="glyphicon glyphicon-arrow-left"></span> Voltar </span>
                    </a>
                {% else %}
                <a href="{% url 'ctb:home' %}">
                        <span class="glyphicon glyphicon-arrow-left"></span> Voltar </span>
                    </a>
                {% endif %}

                <hr>
                <p><strong>Usuário:</strong> {{ userprofile.nome }}
                <strong>Apelido: </strong>{{ userprofile.apelido }}</p>
                <h3>Endereço</h3>
                <hr>
                <p>{{ userprofile.endereco }}
                    <strong>Complemento: </strong>{{ userprofile.complemento }}
                <strong>Bairro: </strong>{{ userprofile.bairro }}
                <strong>Cidade: </strong> {{ userprofile.cidade }}
                <strong>UF: </strong> {{ userprofile.uf }}
                <strong>CEP:</strong>  {{ userprofile.cep }}</p>
                <hr>
                <h3>Acessos</h3>
                <hr>
                <p><strong>Nível de acesso:</strong> {{ userprofile.nivel_acesso }}</p>
                <p><strong>É Supervisor?</strong>  {{ userprofile.supervisor }}</p>
                <p><strong>Segunda-feira:</strong> {{ userprofile.segunda_feira }}
                <strong>Hora Inicial:</strong> {{ userprofile.segunda_hora_inicio }}
                <strong>Hora Final:</strong> {{ userprofile.segunda_hora_final }}</p>
                <p><strong>Terça-feira:</strong> {{ userprofile.terca_feira }}
                <strong>Hora Inicial:</strong> {{ userprofile.terca_hora_inicio }}
                <strong>Hora Final:</strong> {{ userprofile.terca_hora_final }}</p>
                <p><strong>Quarta-feira:</strong> {{ userprofile.quarta_feira }}
                <strong>Hora Inicial:</strong> {{ userprofile.quarta_hora_inicio }}
                <strong>Hora Final:</strong> {{ userprofile.quarta_hora_final }}</p>
                <p><strong>Quinta-feira:</strong> {{ userprofile.quinta_feira }}
                <strong>Hora Inicial:</strong> {{ userprofile.quinta_hora_inicio }}
                <strong>Hora Final:</strong> {{ userprofile.quinta_hora_final }}</p>
                <p><strong>Sexta-feira:</strong> {{ userprofile.sexta_feira }}
                <strong>Hora Inicial:</strong> {{ userprofile.sexta_hora_inicio }}
                <strong>Hora Final:</strong> {{ userprofile.sexta_hora_final }}
                <p><strong>Sábado: </strong>{{ userprofile.sabado }}
                <strong>Hora Inicial:</strong> {{ userprofile.sabado_hora_inicio}}
                <strong>Hora Final:</strong> {{ userprofile.sabado_hora_final }}</p>
                <p><strong>Domingo:</strong> {{ userprofile.domingo }}
                <strong>Hora Inicial:</strong> {{ userprofile.domingo_hora_inicio }}
                <strong>Hora Final:</strong> {{ userprofile.domingo_hora_final }}</p>
                <hr>
                <p><strong>Opera Caixa?</strong> {{ userprofile.opera_caixa }}
                <strong>Número do Check Out:</strong> {{ userprofile.numero_checkout }}</p>
                <p><strong>É Comprador?</strong> {{ userprofile.comprador }}
                <strong>Limite por Compra:</strong> {{ userprofile.limite_por_compra }}
                <strong>Limite de Compra:</strong> {{ userprofile.limite_compra }}</p>
                <p><strong>É Funcionário?</strong> {{ userprofile.funcionario }}
                <strong>É Vendedor?</strong> {{ userprofile.vendedor }}
                <strong>Código do Supervisor:</strong> {{ userprofile.codigo_supervisor }}</p>
                <hr>
                <h3>Comissões</h3>
                <p><strong>Comissão de Venda:</strong> {{ userprofile.comissao_venda }}
                <strong>Comissão sobre Serviços:</strong> {{ userprofile.comissao_sobre_servicos }}
                <strong>Objetivo Mensal de Vendas:</strong> {{ userprofile.objetivo_mensal_vendas }}</p>
                <hr>
                <h3>Informações Bancárias</h3>
                <p><strong>Banco Número:</strong> {{ userprofile.banco_numero }}
                <strong>Banco Dígito Verificador:</strong> {{ userprofile.banco_digito_verficador }}
                <strong>Banco Agência:</strong> {{ userprofile.banco_agencia }}</p>
                <hr>
                <h3>Informações Pessoais</h3>
                <p><strong>Data do Nascimento:</strong> {{ userprofile.data_nascimento | date:"d/m/Y" }}</p>
                <p><strong>Região de Venda:</strong> {{ userprofile.regiao_venda }}</p>
                <p><strong>Departamento: </strong>{{ userprofile.departamento }}</p>
                <p><strong>Matrícula: </strong>{{ userprofile.matricula }}</p>
                <p><strong>Identidade: </strong>{{ userprofile.identidade }}</p>
                <p></p><strong>Data de Emissão: </strong>{{ userprofile.data_emissao }}</p>
                <p><strong>Órgão Emissor: </strong>{{ userprofile.orgao_emissor }}</p>
                <p><strong>Pessoa Física ou Jurídica? </strong>{{ userprofile.fisica_juridica }}</p>
                <p><strong>CPF / CNPJ: </strong>{{ userprofile.cpf_cnpj }}</p>
                <p><strong>Sexo: </strong>{{ userprofile.sexo }}</p>
                <hr>
                <h4>Contatos</h4>
                <p><strong>E-mail: </strong>{{ userprofile.email }}</p>
                <p><strong>(DDD)    Residência:</strong> {{ userprofile.ddd_residencia }}</p>
                <p><strong>Telefone Residência:</strong> {{ userprofile.tel_residencia }}</p>
                <p><strong>(DDD)    Celular:</strong> {{ userprofile.ddd_celular }}</p>
                <p><strong>Telefone Celular: </strong>{{ userprofile.tel_celular }}</p>
                <hr>
                <h4>Informações Adicionais: </h4>
                <p>{{ userprofile.informacoes_adicionais }}</p>

            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/accounts/userprofile/userprofile_form.html
{% extends 'ctb/base_sidebar.html' %}
{% block title %}Novo Perfil de Usuário{% endblock %}
{% block planodecontas_active %}active{% endblock %}

{% block body %}
<div class="col-md-offset-3">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                     <h1>Cadastro de Usuário</h1>
                     <hr>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'ctb/form-template.html' %}
                        <hr>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-4 btn-group">
                                <button type="submit" class="btn btn-success">Gravar</button>
                                <a href="{% url 'accounts:userprofile-list' %}" class="btn btn-primary">Voltar</a>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}