contabilidade/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView

from accounts import views as accounts_views
from ctb import views

urlpatterns = [
                  url(r'^$', views.index, name='index'),
                  url(r'^cart/', include('cart.urls')),
    url(r'^acc/', include('accounts.urls')),
    url(r'^ctb/', include('ctb.urls')),
    url(r'^admin/', admin.site.urls, name='admin'),

                  #
    # AUTENTICAÇÃO
    #
    url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
                  url(r'^signup/$', accounts_views.signup, name='signup'),

    url(r'^reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='password_reset.html',
            email_template_name='password_reset_email.html',
            subject_template_name='password_reset_subject.txt'
        ),
        name='password_reset'),
    url(r'^reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
        name='password_reset_confirm'),
    url(r'^reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
        name='password_reset_complete'),

    url(r'^settings/password/$', auth_views.PasswordChangeView.as_view(template_name='password_change.html'),
        name='password_change'),
    url(r'^settings/password/done/$', auth_views.PasswordChangeDoneView.as_view(
        template_name='password_change_done.html'), name='password_change_done'),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'ctb.views.error_404'
handler500 = 'ctb.views.error_500'

ctb/urls.py
from django.conf.urls import url

from ctb import views
from ctb.views import CompetenciaList, CompetenciaDetalhe, CompetenciaCreate, CompetenciaUpdate, competencia_delete, \
    ContaList, ContaDetalhe, ContaCreate, ContaUpdate, conta_delete, \
    EmpresaList, EmpresaDetalhe, EmpresaCreate, EmpresaUpdate, empresa_delete, \
    HistoricoList, HistoricoDetalhe, HistoricoCreate, HistoricoUpdate, historico_delete, MovimentoContabilHeaderList, \
    MovimentoContabilHeaderCreate, MovimentoContabilHeaderUpdate, movimento_contabil_header_delete, \
    MovimentoContabilHeaderDetalhe, SaldoContaContabilList, SaldoDetalhe, RazaoContabilList, \
    CreateMovimentoContabilHeader, GeneratePdf

app_name = 'ctb'

urlpatterns = [
    # url(r'^$', views.index, name='index'),
    url(r'^home/', views.home, name='home'),

    # Contas
    url(r'^conta-list/$', ContaList.as_view(), name='conta-list'),
    url(r'^conta-list/(?P<pk>[0-9]+)/$', ContaDetalhe.as_view(), name="conta-detail"),
    url(r'^conta-add/$', ContaCreate.as_view(), name='conta-add'),
    url(r'^conta/(?P<pk>[0-9]+)/edit/$', ContaUpdate.as_view(), name='conta-edit'),
    url(r'^conta/(?P<id>[0-9]+)/delete/$', conta_delete, name='conta-delete'),

    # Historicos
    url(r'^historico-list/$', HistoricoList.as_view(), name='historico-list'),
    url(r'^historico-list/(?P<pk>[0-9]+)/$', HistoricoDetalhe.as_view(), name='historico-detail'),
    url(r'^historico-add/$', HistoricoCreate.as_view(), name='historico-add'),
    url(r'^historico/(?P<pk>[0-9]+)/edit/$', HistoricoUpdate.as_view(), name='historico-edit'),
    url(r'^historico/(?P<id>[0-9]+)/delete/$', historico_delete, name='historico-delete'),

    # Empresas
    url(r'^empresa-list/$', EmpresaList.as_view(), name='empresa-list'),
    url(r'^empresa-list/(?P<pk>[0-9]+)/$', EmpresaDetalhe.as_view(), name="empresa-detail"),
    url(r'^empresa-add/$', EmpresaCreate.as_view(), name='empresa-add'),
    url(r'^empresa/(?P<pk>[0-9]+)/edit/$', EmpresaUpdate.as_view(), name='empresa-edit'),
    url(r'^empresa/(?P<id>[0-9]+)/delete/$', empresa_delete, name='empresa-delete'),

    # Competências
    url(r'^competencia-list/$', CompetenciaList.as_view(), name='competencia-list'),
    url(r'^competencia-list/(?P<pk>[0-9]+)/$', CompetenciaDetalhe.as_view(), name='competencia-detail'),
    url(r'^competencia-add/$', CompetenciaCreate.as_view(), name='competencia-add'),
    url(r'^competencia/(?P<pk>[0-9]+)/edit/$', CompetenciaUpdate.as_view(), name='competencia-edit'),
    url(r'^competencia/(?P<id>[0-9]+)/delete/$', competencia_delete, name='competencia-delete'),

    # FORMSET: Lancamento Contabil
    url(r'^lanc-add/$', CreateMovimentoContabilHeader.as_view(), name='lanc-add'),


    # Movimentos Header
    url(r'^movimento-list/$', MovimentoContabilHeaderList.as_view(), name='movimento-list'),
    url(r'^movimento-detalhe/(?P<pk>[0-9]+)/$', MovimentoContabilHeaderDetalhe.as_view(), name='movimento-detail'),
    url(r'^movimento-add/$', MovimentoContabilHeaderCreate.as_view(), name='movimento-add'),
    url(r'^movimento/(?P<pk>[0-9]+)/edit/$', MovimentoContabilHeaderUpdate.as_view(), name='movimento-edit'),
    url(r'^movimento/(?P<id>[0-9]+)/delete/$', movimento_contabil_header_delete, name='movimento-delete'),

    # Lançamentos
    url(r'^(?P<movimentocontabilheader_id>[0-9]+)/create_lancamento/$', views.create_lancamento,
        name='lancamento-add'),
    url(r'^(?P<movimentocontabilheader_id>[0-9]+)/delete_lancamento/(?P<lancamentocontabil_id>[0-9]+)/$',
        views.delete_lancamento, name='lancamento-delete'),
    url(r'^razao_contabil/$', RazaoContabilList.as_view(), name='razao_contabil'),

    # saldo
    url(r'^saldo-lista/$', SaldoContaContabilList.as_view(), name='saldo-list'),
    url(r'^saldo-detalhe/(?P<pk>[0-9]+)/$', SaldoDetalhe.as_view(), name='saldo-detail'),

    # WORK IN PROGRESS
    url(r'^wip/$', views.work_in_progress, name="wip"),

    # ReportLab
    url(r'^pdf/$', GeneratePdf.as_view(), name='generate_pdf'),

]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>{% block title %}Contabilidade{% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Indie+Flower" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    {% block stylesheet %}{% endblock %}  <!-- HERE -->
</head>
<body>
{% block body %}
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Contabilidade</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu"
                aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="mainMenu">
            {% if user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-toggle="dropdown"
                       aria-haspopup="true" aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userMenu">
                        <a class="dropdown-item" href="#">My account</a>
                        <a class="dropdown-item" href="{% url 'password_change' %}">Change password</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'logout' %}">Log out</a>
                    </div>
                </li>
            </ul>
            {% else %}
            <form class="form-inline ml-auto">
                <a href="{% url 'login' %}" class="btn btn-outline-secondary">Log in</a>
                <a href="{% url 'signup' %}" class="btn btn-primary ml-2">Sign up</a>
            </form>
            {% endif %}
        </div>
    </div>
</nav>

<div class="container">
    <ol class="breadcrumb my-4">
        {% block breadcrumb %}
        {% endblock %}
    </ol>
    {% block content %}
    {% endblock %}
</div>
<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script
        src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
        integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
        crossorigin="anonymous">
</script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% endblock body %}
</body>
</html>

templates/base_accounts.html
{% extends 'base.html' %}

{% load static %}

{% block stylesheet %}
<link rel="stylesheet" href="{% static 'css/accounts.css' %}">
{% endblock %}

{% block body %}
<div class="container">
    <h1 class="text-center logo my-4">
        <a href="{% url 'ctb:home' %}">Contabilidade</a>
    </h1>
    {% block content %}
    {% endblock %}
</div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block breadcrumb %}
<li class="breadcrumb-item"><strong>Menu Principal</strong></li>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-sm-2">
        <div class="card text-white text-center bg-warning mb-3" style="max-width: 10rem;">
            <h6 class="card-header">Contas</h6>
            <img class="card-img-top" src="{% static 'ctb/img/marca_edu.jpg' %}" alt="Card image cap">
            <div class="card-body">
                <!--<h4 class="card-title">Contas</h4>-->
                <!--<p class="card-text">Contas</p>-->
                <a href="{% url 'ctb:conta-list' %}" class="btn btn-primary">Iniciar</a>
            </div>
        </div>
    </div>

    <div class="col-sm-2">
        <div class="card text-white text-center bg-warning mb-3" style="max-width: 10rem;">
            <h6 class="card-header">Empresas</h6>
            <img class="card-img-top" src="{% static 'ctb/img/marca_edu.jpg' %}" alt="Card image cap">
            <div class="card-body">
                <!--<h4 class="card-title">Empresas</h4>-->
                <!--<p class="card-text">Empresas</p>-->
                <a href="{% url 'ctb:empresa-list' %}" class="btn btn-primary">Iniciar</a>
            </div>
        </div>
    </div>

    <div class="col-sm-2">
        <div class="card text-white text-center bg-warning mb-3" style="max-width: 10rem;">
            <h6 class="card-header">Históricos</h6>
            <img class="card-img-top" src="{% static 'ctb/img/marca_edu.jpg' %}" alt="Card image cap">
            <div class="card-body">
                <!--<h4 class="card-title">Empresas</h4>-->
                <!--<p class="card-text">Históricos</p>-->
                <a href="{% url 'ctb:historico-list' %}" class="btn btn-primary">Iniciar</a>
            </div>
        </div>
    </div>

    <div class="col-sm-2">
        <div class="card text-white text-center bg-warning mb-3" style="max-width: 10rem;">
            <h6 class="card-header">Competências</h6>
            <img class="card-img-top" src="{% static 'ctb/img/marca_edu.jpg' %}" alt="Card image cap">
            <div class="card-body">
                <!--<h4 class="card-title">Empresas</h4>-->
                <!--<p class="card-text">Competências</p>-->
                <a href="{% url 'ctb:competencia-list' %}" class="btn btn-primary">Iniciar</a>
            </div>
        </div>
    </div>

    <div class="col-sm-2">
        <div class="card text-white text-center bg-warning mb-3" style="max-width: 10rem;">
            <h6 class="card-header">Lançamentos</h6>
            <img class="card-img-top" src="{% static 'ctb/img/marca_edu.jpg' %}" alt="Card image cap">
            <div class="card-body">
                <!--<h4 class="card-title">Empresas</h4>-->
                <!--<p class="card-text">Lançamentos</p>-->
                <a href="{% url 'ctb:movimento-list' %}" class="btn btn-primary">Iniciar</a>
            </div>
        </div>
    </div>

    <div class="col-sm-2">
        <div class="card text-white text-center bg-warning mb-3" style="max-width: 10rem;">
            <h6 class="card-header">Saldos</h6>
            <img class="card-img-top" src="{% static 'ctb/img/marca_edu.jpg' %}" alt="Card image cap">
            <div class="card-body">
                <!--<h4 class="card-title">Empresas</h4>-->
                <!--<p class="card-text">Saldos</p>-->
                <a href="{% url 'ctb:saldo-list' %}" class="btn btn-primary">Iniciar</a>
            </div>
        </div>
    </div>

    <div class="col-sm-2">
        <div class="card text-white text-center bg-dark mb-3" style="max-width: 10rem;">
            <h6 class="card-header">Vago</h6>
            <img class="card-img-top" src="{% static 'ctb/img/marca_edu.jpg' %}" alt="Card image cap">
            <div class="card-body">
                <!--<h4 class="card-title">Empresas</h4>-->
                <!--<p class="card-text">Vago 01</p>-->
                <a href="#" class="btn btn-primary">Iniciar</a>
            </div>
        </div>
    </div>

    <div class="col-sm-2">
        <div class="card text-white text-center bg-dark mb-3" style="max-width: 10rem;">
            <h6 class="card-header">Vago</h6>
            <img class="card-img-top" src="{% static 'ctb/img/marca_edu.jpg' %}" alt="Card image cap">
            <div class="card-body">
                <!--<h4 class="card-title">Empresas</h4>-->
                <!--<p class="card-text">Vago 01</p>-->
                <a href="#" class="btn btn-primary">Iniciar</a>
            </div>
        </div>
    </div>

    <div class="col-sm-2">
        <div class="card text-white text-center bg-dark mb-3" style="max-width: 10rem;">
            <h6 class="card-header">Vago</h6>
            <img class="card-img-top" src="{% static 'ctb/img/marca_edu.jpg' %}" alt="Card image cap">
            <div class="card-body">
                <!--<h4 class="card-title">Empresas</h4>-->
                <!--<p class="card-text">Vago 01</p>-->
                <a href="#" class="btn btn-primary">Iniciar</a>
            </div>
        </div>
    </div>

    <div class="col-sm-2">
        <div class="card text-white text-center bg-dark mb-3" style="max-width: 10rem;">
            <h6 class="card-header">Vago</h6>
            <img class="card-img-top" src="{% static 'ctb/img/marca_edu.jpg' %}" alt="Card image cap">
            <div class="card-body">
                <!--<h4 class="card-title">Empresas</h4>-->
                <!--<p class="card-text">Vago 01</p>-->
                <a href="#" class="btn btn-primary">Iniciar</a>
            </div>
        </div>
    </div>

    <div class="col-sm-2">
        <div class="card text-white text-center bg-dark mb-3" style="max-width: 10rem;">
            <h6 class="card-header">Vago</h6>
            <img class="card-img-top" src="{% static 'ctb/img/marca_edu.jpg' %}" alt="Card image cap">
            <div class="card-body">
                <!--<h4 class="card-title">Empresas</h4>-->
                <!--<p class="card-text">Vago 01</p>-->
                <a href="#" class="btn btn-primary">Iniciar</a>
            </div>
        </div>
    </div>

    <div class="col-sm-2">
        <div class="card text-white text-center bg-dark mb-3" style="max-width: 10rem;">
            <h6 class="card-header">Vago</h6>
            <img class="card-img-top" src="{% static 'ctb/img/marca_edu.jpg' %}" alt="Card image cap">
            <div class="card-body">
                <!--<h4 class="card-title">Empresas</h4>-->
                <!--<p class="card-text">Vago 01</p>-->
                <a href="#" class="btn btn-primary">Iniciar</a>
            </div>
        </div>
    </div>


</div>
{% endblock %}

templates/index.html
<!doctype html>
<html lang="en">
{% load static %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static ctb/img/favicon.ico">

    <style>
        .orangetext {
            color: orange;
        }

        .bluetext {
            color: blue;
        }

        .redtext {
            color: red;
        }

        .greentext {
            color: green;
        }


    </style>

    <title>Contabilidade</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/carousel.css' %}" rel="stylesheet">

</head>
<body>
<header>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="{% url 'index' %}">Usesoft</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#">Disabled</a>
                </li>
            </ul>
            <form class="form-inline mt-2 mt-md-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
</header>

<main role="main">

    <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="first-slide"
                     src="{% static 'img/business01.jpg' %}"
                     alt="Primeiro slide">
                <div class="container">
                    <div class="carousel-caption text-left">
                        <h1 class="redtext">Sistema de Contabilidade</h1>
                        <p class="greentext">A contabilidade é uma ferramenta de fundamental importância para o controle
                            de um
                            empreendimento. Por meio dela é possível extrair uma série de informações importantes para a
                            tomada de decisão, para controlar e acompanhar as operações, além de facilitar o
                            planejamento como um todo.</p>
                        <p><a class="btn btn-lg btn-success" href="{% url 'ctb:home' %}" role="button">Iniciar</a></p>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <img class="second-slide"
                     src="{% static 'img/business02.jpg' %}"
                     alt="Segundo slide">
                <div class="container">
                    <div class="carousel-caption">
                        <h1 class="redtext">SPED Contábil</h1>
                        <p class="redtext">De maneira geral, as empresas devem registrar por meio do SPED Contábil todas
                            as transições
                            pertinentes à sua vida contábil. Os dados devem ter identificação de data, partes envolvidas
                            (CPF ou CNPJ), documentos de registro e classificação contábil. Tudo deve ser transmitido em
                            arquivos eletrônicos para a Receita Federal. Assim, ela terá à disposição um banco de dados
                            gigantesco capaz de cruzar informações às quais não teria acesso em anos anteriores.</p>
                        <p><a class="btn btn-lg btn-success" href="{% url 'ctb:home' %}" role="button">Iniciar</a></p>
                    </div>
                </div>
            </div>
            <div class="carousel-item">
                <img class="third-slide"
                     src="{% static 'img/business03.jpg' %}"
                     alt="Terceiro slide">
                <div class="container">
                    <div class="carousel-caption text-right">
                        <h1 class="redtext">Quando o SPED Contábil deve ser entregue?</h1>
                        <p class="redtext">Desde 2016, a entrega do SPED Contábil deve ser feita até o último dia útil
                            do do mês de maio
                            no ano-calendário subsequente ao da escrituração. Esse prazo não pode ser postegado e a
                            não-entrega acarretará em multa.

                            Ou seja, em 2017, o SPED Contábil deve ser entregue até às 23h59min59s (horário de
                            Brasília)do dia 31 de maio.</p>
                        <p><a class="btn btn-lg btn-success" href="{% url 'ctb:home' %}" role="button">Iniciar</a></p>
                    </div>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#myCarousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Anterior</span>
        </a>
        <a class="carousel-control-next" href="#myCarousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Próximo</span>
        </a>
    </div>


    <!-- FOOTER -->
    <footer class="container">
        <p>&copy; 2017 Usesoft do Brasil Informática.</p>
    </footer>

</main>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="{% static 'js/jquery.min.js' %}"><\/script>')</script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- Just to make our placeholder images work. Don't actually copy the next line! -->
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

templates/login.html
{% extends 'base_accounts.html' %}

{% block title %}Log in to Contabilidade{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title">Log in</h3>
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% include 'includes/form.html' %}
                    <button type="submit" class="btn btn-primary btn-block">Log in</button>
                </form>
            </div>
            <div class="card-footer text-muted text-center">
                New to Django Boards? <a href="{% url 'signup' %}">Sign up</a>
            </div>
        </div>
        <div class="text-center py-2">
            <small>
                <a href="{% url 'password_reset' %}" class="text-muted">Esqueceu a Senha?</a>
            </small>
        </div>
    </div>
</div>
{% endblock %}

templates/password_change.html
{% extends 'base.html' %}

{% block title %}Change password{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item active">Change password</li>
{% endblock %}

{% block content %}
<div class="row">
    <div class="col-lg-6 col-md-8 col-sm-10">
        <form method="post" novalidate>
            {% csrf_token %}
            {% include 'includes/form.html' %}
            <button type="submit" class="btn btn-success">Change password</button>
        </form>
    </div>
</div>
{% endblock %}

templates/password_change_done.html
{% extends 'base.html' %}

{% block title %}Change password successful{% endblock %}

{% block breadcrumb %}
<li class="breadcrumb-item"><a href="{% url 'password_change' %}">Change password</a></li>
<li class="breadcrumb-item active">Success</li>
{% endblock %}

{% block content %}
<div class="alert alert-success" role="alert">
    <strong>Success!</strong> Your password has been changed!
</div>
<a href="{% url 'home' %}" class="btn btn-secondary">Return to home page</a>
{% endblock %}

templates/password_reset.html
{% extends 'base_accounts.html' %}

{% block title %}Reset your password{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title">Reset your password</h3>
                <p>Enter your email address and we will send you a link to reset your password.</p>
                <form method="post" novalidate>
                    {% csrf_token %}
                    {% include 'includes/form.html' %}
                    <button type="submit" class="btn btn-primary btn-block">Send password reset email</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/password_reset_done.html
{% extends 'base_accounts.html' %}

{% block title %}Reset your password{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-lg-4 col-md-6 col-sm-8">
        <div class="card">
            <div class="card-body">
                <h3 class="card-title">Reset your password</h3>
                <p>Check your email for a link to reset your password. If it doesn't appear within a few minutes, check
                    your spam folder.</p>
                <a href="{% url 'login' %}" class="btn btn-secondary btn-block">Return to log in</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/password_reset_email.html
Olá,


Alguém solicitou uma mudança de senha pelo endereço de email {{ email }}.

Siga o link abaixo:
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

Caso você tenha esquecido seu usuário da Contabilidade: {{ user.username }}

Se por acaso, ao clicar sobre o link não funcionar, por favor copie e cole a URL
em uma nova janela do browser.

Se você recebeu esse email por engano, é provável que outro usuário entrou com
o seu endereço de email indevidamente enquanto tentava mudar a senha. Se você não
iniciou essa solicitação, você não precisa fazer nada e pode tranquilamente descartar
essa mensagem.

Obrigado,

A Equipe da Contabilidade
Usesoft do Brasil

templates/pdf_template.html
<html>
<head>
    <title>Test</title>
    <style>
    body {
      background-color: #f7f7f7;
    }

    </style>
</head>
<body>
<h1>Test Template</h1>
{% for paragraph in paragraphs %}
<p>{{ paragraph }}</p>
{% endfor %}
</body>
</html>

templates/signup.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <h2>Sign up</h2>
    <form method="post" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-primary">Create an account</button>
    </form>
</div>
{% endblock %}

templates/wip.html
{% extends 'ctb/base_sidebar.html' %}
{% load static %}
{% block body %}
<div class="container">
    <div class="col-md-offset-2">
          <h1 class="page-header">{{ title }}</h1>

          <div class="row">


              <a href="{% url 'index' %}">
                  <img src="{% static 'img/work-in-progress.jpeg' %}" alt="Work In Progress"
                       style="width:304px;height:228px;">
              </a>

          </div>

        </div>
</div>
</div>
{% endblock %}