contabilidade/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView

from accounts import views as accounts_views
from ctb import views

urlpatterns = [
                  url(r'^$', views.index, name='index'),
                  url(r'^cart/', include('cart.urls')),
    url(r'^acc/', include('accounts.urls')),
    url(r'^ctb/', include('ctb.urls')),
    url(r'^admin/', admin.site.urls, name='admin'),

                  #
    # AUTENTICAÇÃO
    #
    url(r'^login/$', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
                  url(r'^signup/$', accounts_views.signup, name='signup'),

    url(r'^reset/$',
        auth_views.PasswordResetView.as_view(
            template_name='password_reset.html',
            email_template_name='password_reset_email.html',
            subject_template_name='password_reset_subject.txt'
        ),
        name='password_reset'),
    url(r'^reset/done/$',
        auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
        name='password_reset_confirm'),
    url(r'^reset/complete/$',
        auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
        name='password_reset_complete'),

    url(r'^settings/password/$', auth_views.PasswordChangeView.as_view(template_name='password_change.html'),
        name='password_change'),
    url(r'^settings/password/done/$', auth_views.PasswordChangeDoneView.as_view(
        template_name='password_change_done.html'), name='password_change_done'),

              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'ctb.views.error_404'
handler500 = 'ctb.views.error_500'

ctb/urls.py
from django.conf.urls import url

from ctb import views
from ctb.views import CompetenciaList, CompetenciaDetalhe, CompetenciaCreate, CompetenciaUpdate, competencia_delete, \
    ContaList, ContaDetalhe, ContaCreate, ContaUpdate, conta_delete, \
    EmpresaList, EmpresaDetalhe, EmpresaCreate, EmpresaUpdate, empresa_delete, \
    HistoricoList, HistoricoDetalhe, HistoricoCreate, HistoricoUpdate, historico_delete, MovimentoContabilHeaderList, \
    MovimentoContabilHeaderCreate, MovimentoContabilHeaderUpdate, movimento_contabil_header_delete, \
    MovimentoContabilHeaderDetalhe, SaldoContaContabilList, SaldoDetalhe, RazaoContabilList, \
    CreateMovimentoContabilHeader, GeneratePdf

app_name = 'ctb'

urlpatterns = [
    # url(r'^$', views.index, name='index'),
    url(r'^home/', views.home, name='home'),

    # Contas
    url(r'^conta-list/$', ContaList.as_view(), name='conta-list'),
    url(r'^conta-list/(?P<pk>[0-9]+)/$', ContaDetalhe.as_view(), name="conta-detail"),
    url(r'^conta-add/$', ContaCreate.as_view(), name='conta-add'),
    url(r'^conta/(?P<pk>[0-9]+)/edit/$', ContaUpdate.as_view(), name='conta-edit'),
    url(r'^conta/(?P<id>[0-9]+)/delete/$', conta_delete, name='conta-delete'),

    # Historicos
    url(r'^historico-list/$', HistoricoList.as_view(), name='historico-list'),
    url(r'^historico-list/(?P<pk>[0-9]+)/$', HistoricoDetalhe.as_view(), name='historico-detail'),
    url(r'^historico-add/$', HistoricoCreate.as_view(), name='historico-add'),
    url(r'^historico/(?P<pk>[0-9]+)/edit/$', HistoricoUpdate.as_view(), name='historico-edit'),
    url(r'^historico/(?P<id>[0-9]+)/delete/$', historico_delete, name='historico-delete'),

    # Empresas
    url(r'^empresa-list/$', EmpresaList.as_view(), name='empresa-list'),
    url(r'^empresa-list/(?P<pk>[0-9]+)/$', EmpresaDetalhe.as_view(), name="empresa-detail"),
    url(r'^empresa-add/$', EmpresaCreate.as_view(), name='empresa-add'),
    url(r'^empresa/(?P<pk>[0-9]+)/edit/$', EmpresaUpdate.as_view(), name='empresa-edit'),
    url(r'^empresa/(?P<id>[0-9]+)/delete/$', empresa_delete, name='empresa-delete'),

    # Competências
    url(r'^competencia-list/$', CompetenciaList.as_view(), name='competencia-list'),
    url(r'^competencia-list/(?P<pk>[0-9]+)/$', CompetenciaDetalhe.as_view(), name='competencia-detail'),
    url(r'^competencia-add/$', CompetenciaCreate.as_view(), name='competencia-add'),
    url(r'^competencia/(?P<pk>[0-9]+)/edit/$', CompetenciaUpdate.as_view(), name='competencia-edit'),
    url(r'^competencia/(?P<id>[0-9]+)/delete/$', competencia_delete, name='competencia-delete'),

    # FORMSET: Lancamento Contabil
    url(r'^lanc-add/$', CreateMovimentoContabilHeader.as_view(), name='lanc-add'),


    # Movimentos Header
    url(r'^movimento-list/$', MovimentoContabilHeaderList.as_view(), name='movimento-list'),
    url(r'^movimento-detalhe/(?P<pk>[0-9]+)/$', MovimentoContabilHeaderDetalhe.as_view(), name='movimento-detail'),
    url(r'^movimento-add/$', MovimentoContabilHeaderCreate.as_view(), name='movimento-add'),
    url(r'^movimento/(?P<pk>[0-9]+)/edit/$', MovimentoContabilHeaderUpdate.as_view(), name='movimento-edit'),
    url(r'^movimento/(?P<id>[0-9]+)/delete/$', movimento_contabil_header_delete, name='movimento-delete'),

    # Lançamentos
    url(r'^(?P<movimentocontabilheader_id>[0-9]+)/create_lancamento/$', views.create_lancamento,
        name='lancamento-add'),
    url(r'^(?P<movimentocontabilheader_id>[0-9]+)/delete_lancamento/(?P<lancamentocontabil_id>[0-9]+)/$',
        views.delete_lancamento, name='lancamento-delete'),
    url(r'^razao_contabil/$', RazaoContabilList.as_view(), name='razao_contabil'),

    # saldo
    url(r'^saldo-lista/$', SaldoContaContabilList.as_view(), name='saldo-list'),
    url(r'^saldo-detalhe/(?P<pk>[0-9]+)/$', SaldoDetalhe.as_view(), name='saldo-detail'),

    # WORK IN PROGRESS
    url(r'^wip/$', views.work_in_progress, name="wip"),

    # ReportLab
    url(r'^pdf/$', GeneratePdf.as_view(), name='generate_pdf'),

]

ctb/views.py
# coding=utf-8
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db import transaction
from django.db.models import Q, Max
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView
from django.views.generic.base import View

from contabilidade.utils import render_to_pdf
from ctb.forms import ContaForm, LancamentoContabilForm, MovimentoContabilHeaderForm, LancamentoContabilFormSet
from ctb.models import Conta, Historico, Empresa, Competencia, MovimentoContabilHeader, LancamentoContabil, \
    SaldoContaContabil

"""
    PÁGINA PRINCIPAL DA CONTABILIDADE
"""


def index(request):
    empresa = Empresa.objects.all()
    context = {
                'title': 'Menu Principal',
                'current_user': request.user,
        'empresa': empresa
    }

    return render(request, "index.html", context)


@login_required()
def home(request):
    empresa = Empresa.objects.all()
    context = {
        'title': 'Home',
        'current_user': request.user,
        'empresa': empresa
    }

    return render(request, "home.html", context)


"""
       PLANO DE CONTAS
"""


class ContaList(SuccessMessageMixin, LoginRequiredMixin, ListView):
    model = Conta
    template_name = "ctb/conta/conta-list.html"

    def get_queryset(self):
        valor = self.request.GET.get('q')
        if valor:
            object_list = self.model.objects.filter(
                Q(codigo_conta__startswith=valor) |
                Q(codigo_conta__icontains=valor) |
                Q(conta__conta_superior__contains=valor) |
                Q(descricao__contains=valor.upper()) |
                Q(descricao__icontains=valor.title()) |
                Q(origem__icontains=valor) |
                Q(natureza__icontains=valor)
            )
        else:
            object_list = self.model.objects.all()

        paginator = Paginator(object_list, 10)  # Show 10 contas per page

        page = self.request.GET.get('page')
        try:
            queryset = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            queryset = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            queryset = paginator.page(paginator.num_pages)

        # return object_list
        return queryset


class ContaDetalhe(SuccessMessageMixin, LoginRequiredMixin, DetailView):
    model = Conta
    template_name = "ctb/conta/conta_detail.html"

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            calculated_field=self.object.descricao,
        )


class ContaCreate(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Conta
    form_class = ContaForm
    success_message = '%(descricao)s criado com sucesso!'
    template_name = "ctb/conta/conta_form.html"

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            calculated_field=self.object.descricao,
        )


class ContaUpdate(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Conta
    fields = '__all__'
    success_message = '%(descricao)s alterado com sucesso!'
    template_name = "ctb/conta/conta_form.html"

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            calculated_field=self.object.descricao,
        )


def conta_delete(request, id=None):
    obj = get_object_or_404(Conta, id=id)
    if request.method == 'POST':
        obj.delete()
        messages.success(request, 'Registro apagado com sucesso!')
        return redirect('ctb:conta-list')

    context = {
        'object': obj
    }

    return render(request, 'ctb/confirm_delete.html', context)


"""
    WORK IN PROGRESS
"""


def work_in_progress(request):
    return render(request, "wip.html", {})

"""
    Historico - GENERIC VIEWS
"""


class HistoricoList(SuccessMessageMixin, LoginRequiredMixin, ListView):
    model = Historico
    template_name = 'ctb/historico/historico-list.html'

    def get_queryset(self):
        descricao = self.request.GET.get('q')
        if descricao:
            object_list = self.model.objects.filter(descricao__icontains=descricao)
        else:
            object_list = self.model.objects.all()

        paginator = Paginator(object_list, 9)  # Show 9 contas per page

        page = self.request.GET.get('page')
        try:
            queryset = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            queryset = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            queryset = paginator.page(paginator.num_pages)

        # return object_list
        return queryset


class HistoricoDetalhe(SuccessMessageMixin, LoginRequiredMixin, DetailView):
    model = Historico
    template_name = 'ctb/historico/historico_detail.html'


class HistoricoCreate(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Historico
    fields = '__all__'
    success_message = '%(descricao)s criado com sucesso!'
    template_name = "ctb/historico/historico_form.html"

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            calculated_field=self.object.descricao,
        )


class HistoricoUpdate(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Historico
    fields = '__all__'
    success_message = '%(descricao)s alterado com sucesso!'
    template_name = 'ctb/historico/historico_form.html'

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            calculated_field=self.object.descricao,
        )


def historico_delete(request, id=None):
    obj = get_object_or_404(Historico, id=id)
    if request.method == 'POST':
        obj.delete()
        messages.success(request, 'Registro apagado com sucesso!')
        return redirect('ctb:historico-list')

    context = {
        'object': obj
    }

    return render(request, 'ctb/confirm_delete.html', context)

"""
       EMPRESA
"""


class EmpresaList(SuccessMessageMixin, LoginRequiredMixin, ListView):
    model = Empresa
    template_name = "ctb/empresa/empresa-list.html"

    def get_queryset(self):
        razao_social = self.request.GET.get('q')
        if razao_social:
            object_list = self.model.objects.filter(razao_social__icontains=razao_social)
        else:
            object_list = self.model.objects.all()

        paginator = Paginator(object_list, 9)  # Show 10 contas per page

        page = self.request.GET.get('page')
        try:
            queryset = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            queryset = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            queryset = paginator.page(paginator.num_pages)

        # return object_list
        return queryset


class EmpresaDetalhe(SuccessMessageMixin, LoginRequiredMixin, DetailView):
    model = Empresa
    success_message = 'Detalhe registro apresentado com sucesso!'
    template_name = "ctb/empresa/empresa_detail.html"

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            calculated_field=self.object.razao_social,
        )


class EmpresaCreate(SuccessMessageMixin, LoginRequiredMixin, CreateView):
    model = Empresa
    fields = '__all__'
    success_message = '%(razao_social)s criado com sucesso!'
    template_name = "ctb/empresa/empresa_form.html"

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            calculated_field=self.object.razao_social,
        )


class EmpresaUpdate(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Empresa
    fields = '__all__'
    success_message = '%(razao_social)s alterado com sucesso!'
    template_name = "ctb/empresa/empresa_form.html"

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            calculated_field=self.object.razao_social,
        )


def empresa_delete(request, id=None):
    obj = get_object_or_404(Empresa, id=id)
    if request.method == 'POST':
        obj.delete()
        messages.success(request, 'Registro apagado com sucesso!')
        return redirect('ctb:empresa-list')

    context = {
        'object': obj
    }

    return render(request, 'ctb/confirm_delete.html', context)


"""
    Competencia - GENERIC VIEWS
"""


class CompetenciaList(SuccessMessageMixin, LoginRequiredMixin, ListView):
    model = Competencia
    template_name = 'ctb/competencia/competencia-list.html'

    def get_queryset(self):
        data_competencia = self.request.GET.get('q')
        if data_competencia:
            object_list = self.model.objects.filter(data_competencia__icontains=data_competencia)
        else:
            object_list = self.model.objects.all()

        paginator = Paginator(object_list, 10)  # Show 10 contas per page

        page = self.request.GET.get('page')
        try:
            queryset = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.

templates/ctb/competencia/competencia-list.html
{% extends 'ctb/base_sidebar.html' %}
{% block competencia_active %}active{% endblock %}

{% block body %}

    <!-- historicos -->
<div class="container">
    <div class="col-md-offset-2">
        <div class="panel panel-default">
            <div class="row">

                <div class="col-xs-3 .col-sm-3 .col-md-3">
                    <h4 style="margin-left: 10px; margin-top: 10px;"><strong>Lista de Competências</strong></h4>
                </div>


                <!-- Pesquisa -->
                <div class="col-xs-3 .col-sm-3 .col-md-3">
                    <form method="GET" action="" id="searchform" style="margin-top: 0px;">
                        {% csrf_token %}
                        <input class="input-lg input-search" id="searchbox" name="q" type="text" value="{{ request.GET.q }}"
                            placeholder="Pesquisa...">
                    </form>
                </div>

                <div class="btn-group">
                    <!-- PDF -->
                    <a href="#">
                        <button type="button" disabled class="btn btn-warning" data-toggle="tooltip" title="Gera PDF"
                                style="margin-top: 4px;">
                            <span class="glyphicon glyphicon-download-alt"></span>&nbsp; PDF
                        </button>
                    </a>

                    <!-- EXCEL -->
                    <a href="#">
                        <button type="button" disabled class="btn btn-warning" data-toggle="tooltip" title="Gera Excel"
                                style="margin-top: 4px;">
                            <span class="glyphicon glyphicon-download-alt"></span>&nbsp; Excel
                        </button>
                    </a>

                    <!-- Botão Cria Registro -->
                    <a href="{% url 'ctb:competencia-add' %}">
                        <button type="button" class="btn btn-success" data-toggle="tooltip" title="Cria um novo registro"
                                style="margin-top: 4px;">
                            <span class="glyphicon glyphicon-plus"></span>&nbsp; Novo registro
                        </button>
                    </a>

                </div>
            </div>

        </div>
        {% if object_list %}
                <table class=" responsive table table-responsive table-condensed table-bordered table-hover table-striped"
                   style="margin-bottom: 0px;">
                    <tbody>
                        <tr>
                            <th>Competência</th>
                            <th>Status</th>
                        </tr>
                        <tfoot>
                            <tr>
                                <th>Competência</th>
                                <th>Status</th>
                            </tr>
                        </tfoot>
                        {% for competencia in object_list %}
                            {% if competencia.status == 'A' %}
                                <tr>

                                <td>{{ competencia.data_competencia  }}</td>
                                <td>{{ competencia.status}}</td>

                                <!-- Detalhes -->
                                <td>
                                    <div class="btn-group">
                                            <!-- Edita -->
                                             <a href="{% url 'ctb:competencia-edit' competencia.id %}"
                                                    class="btn btn-primary btn-sm" role="button" data-toggle="tooltip"
                                                    title="Altera o registro">
                                                    <span class="glyphicon glyphicon-edit"></span>
                                             </a>

                                            <!-- Deleta -->
                                            <form action="{% url 'ctb:competencia-delete' competencia.id %}"
                                                   style="display: inline;">
                                                {% csrf_token %}
                                                <input type="hidden"   />
                                                    <button type="submit" class="btn btn-danger btn-sm" data-toggle="tooltip"
                                                            title="Exclui o registro">
                                                        <span class="glyphicon glyphicon-trash"></span>
                                                    </button>
                                            </form>
                                    </div>
                                </td>
                            </tr>
                            {% else %}
                                <tr class="danger">

                                <td>{{ competencia.data_competencia  }}</td>
                                <td>{{ competencia.status}}</td>

                                <!-- Detalhes -->
                                <td>
                                    <div class="btn-group">
                                        <!-- Edita -->
                                            <a href="{% url 'ctb:competencia-edit' competencia.id %}"
                                                class="btn btn-primary btn-sm" role="button" data-toggle="tooltip"
                                                title="Altera o registro">
                                                <span class="glyphicon glyphicon-edit"></span>
                                            </a>

                                            <!-- Deleta -->
                                            <form action="{% url 'ctb:competencia-delete' competencia.id %}"
                                                   style="display: inline;">
                                                {% csrf_token %}
                                                <input type="hidden"   />
                                                    <button type="submit" class="btn btn-danger btn-sm" data-toggle="tooltip"
                                                            title="Exclui o registro">
                                                        <span class="glyphicon glyphicon-trash"></span>
                                                    </button>
                                            </form>
                                    </div>
                                </td>
                            </tr>
                            {% endif %}


                        {% endfor %}




                    </tbody>

                    <script>
                         $(document).ready(function(){
                         $('[data-toggle="tooltip"]').tooltip();
                          });
                    </script>

                </table>

                <div class="col-md-offset-2" align="right">
                <div class="pagination">
                    <span class="step-links">
                        {% if object_list.has_previous %}
                            <a href="?page={{ object_list.previous_page_number }}">
                                <span data-toggle="tooltip" title="Página anterior" class="glyphicon glyphicon-triangle-left" aria-hidden="true"></span></a>
                        {% endif %}

                        <span class="current">
                            Página {{ object_list.number }} de {{ object_list.paginator.num_pages }}
                        </span>

                        {% if object_list.has_next %}
                            <a href="?page={{ object_list.next_page_number }}">
                                <span data-toggle="tooltip" title="Página seguinte" class="glyphicon glyphicon-triangle-right" aria-hidden="true"></span></a>
                        {% endif %}
                    </span>
                </div>
                </div>

        {% else %}
            <h1>Não existem Competências Cadastradas</h1>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/ctb/competencia/competencia_detail.html
{% extends 'ctb/base_sidebar.html' %}


{% block body %}
<div class="col-md-offset-3">

    <!-- Histórico Padrão Info -->
    <h1>{{ competencia.data_competencia }}</h1>
    <div class="col-sm-4 col-md-6">
        <div class="panel panel-default">
            <div class="panel-body">
                <a href="{% url 'ctb:competencia-list' %}">
                   <span class="glyphicon glyphicon-arrow-left"></span>  Voltar
                </a>
            </div>

            <h3>Status: {{ competencia.status }}</h3>
        </div>

    </div>

</div>
{% endblock %}

templates/ctb/competencia/competencia_form.html
{% extends 'ctb/base_sidebar.html' %}
{% block historicos_active %}active{% endblock %}

{% block body %}
<div class="col-md-offset-3">
    <div class="row">
        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                     <h1>Cadastro de Competências</h1>
                    <hr>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'ctb/form-template.html' %}
                        <hr>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-4 btn-group">
                                <button type="submit" class="btn btn-success">Gravar</button>
                                <a href="{% url 'ctb:competencia-list' %}" class="btn btn-primary">Voltar</a>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}